server:
  port: 8080
spring:
  datasource:
    username: root
    password: zyydd1021
    url: jdbc:mysql://localhost:3306/forumdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host:127.0.0.1
    port:6379
  main:
    allow-circular-references:
      true
  jackson:
    default-property-inclusion: non_null
  mvc:
    async:
      request-timeout: 10000
mybatis:
  type-aliases-package: com.app.entity

